// Code generated by protoc-gen-go. DO NOT EDIT.
// source: portal_intr_rpc.proto

/*
Package gameproto is a generated protocol buffer package.

It is generated from these files:
	portal_intr_rpc.proto

It has these top-level messages:
	PingReqProto
	PingRespProto
*/
package gameproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingReqProto struct {
}

func (m *PingReqProto) Reset()                    { *m = PingReqProto{} }
func (m *PingReqProto) String() string            { return proto.CompactTextString(m) }
func (*PingReqProto) ProtoMessage()               {}
func (*PingReqProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PingRespProto struct {
}

func (m *PingRespProto) Reset()                    { *m = PingRespProto{} }
func (m *PingRespProto) String() string            { return proto.CompactTextString(m) }
func (*PingRespProto) ProtoMessage()               {}
func (*PingRespProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*PingReqProto)(nil), "proto.game.PingReqProto")
	proto.RegisterType((*PingRespProto)(nil), "proto.game.PingRespProto")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PortalIntrService service

type PortalIntrServiceClient interface {
	Ping(ctx context.Context, in *PingReqProto, opts ...grpc.CallOption) (*PingRespProto, error)
}

type portalIntrServiceClient struct {
	cc *grpc.ClientConn
}

func NewPortalIntrServiceClient(cc *grpc.ClientConn) PortalIntrServiceClient {
	return &portalIntrServiceClient{cc}
}

func (c *portalIntrServiceClient) Ping(ctx context.Context, in *PingReqProto, opts ...grpc.CallOption) (*PingRespProto, error) {
	out := new(PingRespProto)
	err := grpc.Invoke(ctx, "/proto.game.PortalIntrService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PortalIntrService service

type PortalIntrServiceServer interface {
	Ping(context.Context, *PingReqProto) (*PingRespProto, error)
}

func RegisterPortalIntrServiceServer(s *grpc.Server, srv PortalIntrServiceServer) {
	s.RegisterService(&_PortalIntrService_serviceDesc, srv)
}

func _PortalIntrService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingReqProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalIntrServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.game.PortalIntrService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalIntrServiceServer).Ping(ctx, req.(*PingReqProto))
	}
	return interceptor(ctx, in, info, handler)
}

var _PortalIntrService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.game.PortalIntrService",
	HandlerType: (*PortalIntrServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PortalIntrService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portal_intr_rpc.proto",
}

func init() { proto.RegisterFile("portal_intr_rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0xc8, 0x2f, 0x2a,
	0x49, 0xcc, 0x89, 0xcf, 0xcc, 0x2b, 0x29, 0x8a, 0x2f, 0x2a, 0x48, 0xd6, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x02, 0x53, 0x7a, 0xe9, 0x89, 0xb9, 0xa9, 0x4a, 0x7c, 0x5c, 0x3c, 0x01, 0x99,
	0x79, 0xe9, 0x41, 0xa9, 0x85, 0x01, 0x20, 0x41, 0x25, 0x7e, 0x2e, 0x5e, 0x08, 0xbf, 0xb8, 0x00,
	0x2c, 0x60, 0x14, 0xc0, 0x25, 0x18, 0x00, 0x36, 0xc5, 0x33, 0xaf, 0xa4, 0x28, 0x38, 0xb5, 0xa8,
	0x2c, 0x33, 0x39, 0x55, 0xc8, 0x9a, 0x8b, 0x05, 0xa4, 0x4a, 0x48, 0x42, 0x0f, 0x61, 0x94, 0x1e,
	0xb2, 0x39, 0x52, 0x92, 0x98, 0x32, 0x50, 0x13, 0x9d, 0xb8, 0xa3, 0x38, 0x41, 0xa2, 0x60, 0xf9,
	0x24, 0x36, 0x30, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xce, 0x6f, 0xdb, 0xab, 0x00,
	0x00, 0x00,
}
